var bookStore = angular.module('bookStoreApp',['bookStoreCtrls','ngRoute']);
bookStore.config(function($routeProvider){
	$routeProvider.when('/hello',{
		templateUrl:'tpls/hello.html',
		controller:'HelloCtrl'
	}).when('/list',{
		templateUrl:'tpls/bookList.html',
		controller:'BookListCtrl'
	}).when('/form',{
		templateUrl:'tpls/form.html',
		controller:"formCtrl"
	}).when('/css',{
		templateUrl:'tpls/css.html',
		controller:"cssCtrl"
	}).when('/ngshow',{
		templateUrl:'tpls/ngshow.html',
		controller:"ngShowCtrl"
	}).otherwise({
		redirectTo:'hello'
	});
});